# Generated by Django 4.1 on 2022-09-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_artist_listing_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
