# Generated by Django 4.1 on 2022-09-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='open_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
