# Generated by Django 4.1 on 2022-09-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_actual_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='actual_price',
        ),
    ]
