# Generated by Django 4.1 on 2022-09-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_bid_bid_alter_listing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchers', to='auctions.listing'),
        ),
    ]
