# Generated by Django 4.1 on 2022-09-09 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_user_total_watched_remove_user_watchlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='total_watched',
        ),
    ]
