# Generated by Django 4.1 on 2022-09-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_listing_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_it_in_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
