# Generated by Django 4.1 on 2022-09-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_remove_listing_is_it_in_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('1', 'Antiques'), ('2', 'Drawing'), ('3', 'Watercolor'), ('4', 'Design'), ('5', 'Miniature'), ('6', 'Painting'), ('7', 'Photography'), ('8', 'Sculpture'), ('9', 'Prints'), ('10', 'Other')], max_length=10),
        ),
    ]
