# Generated by Django 4.1 on 2022-09-13 08:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Antiques'), (2, 'Drawing'), (3, 'Watercolor'), (4, 'Design'), (5, 'Miniature'), (6, 'Painting'), (7, 'Photography'), (8, 'Sculpture'), (9, 'Prints'), (10, 'Oil'), (11, 'Acrylic'), (12, 'Original artwork')], max_length=3),
        ),
    ]
