# Generated by Django 4.1 on 2022-09-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_alter_listing_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='avatar',
            field=models.URLField(blank=True, default=''),
        ),
    ]
