# Generated by Django 4.1 on 2022-09-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_alter_listing_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='avatar',
            field=models.URLField(blank=True, default='https://static.vecteezy.com/system/resources/previews/004/141/669/original/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector.jpg'),
        ),
    ]
